services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA : "Y"
      SA_PASSWORD : "Password123"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"